package com.muses.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InsureApplicantInfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public InsureApplicantInfoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAppInfoIdIsNull() {
            addCriterion("app_info_id is null");
            return (Criteria) this;
        }

        public Criteria andAppInfoIdIsNotNull() {
            addCriterion("app_info_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppInfoIdEqualTo(Long value) {
            addCriterion("app_info_id =", value, "appInfoId");
            return (Criteria) this;
        }

        public Criteria andAppInfoIdNotEqualTo(Long value) {
            addCriterion("app_info_id <>", value, "appInfoId");
            return (Criteria) this;
        }

        public Criteria andAppInfoIdGreaterThan(Long value) {
            addCriterion("app_info_id >", value, "appInfoId");
            return (Criteria) this;
        }

        public Criteria andAppInfoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("app_info_id >=", value, "appInfoId");
            return (Criteria) this;
        }

        public Criteria andAppInfoIdLessThan(Long value) {
            addCriterion("app_info_id <", value, "appInfoId");
            return (Criteria) this;
        }

        public Criteria andAppInfoIdLessThanOrEqualTo(Long value) {
            addCriterion("app_info_id <=", value, "appInfoId");
            return (Criteria) this;
        }

        public Criteria andAppInfoIdIn(List<Long> values) {
            addCriterion("app_info_id in", values, "appInfoId");
            return (Criteria) this;
        }

        public Criteria andAppInfoIdNotIn(List<Long> values) {
            addCriterion("app_info_id not in", values, "appInfoId");
            return (Criteria) this;
        }

        public Criteria andAppInfoIdBetween(Long value1, Long value2) {
            addCriterion("app_info_id between", value1, value2, "appInfoId");
            return (Criteria) this;
        }

        public Criteria andAppInfoIdNotBetween(Long value1, Long value2) {
            addCriterion("app_info_id not between", value1, value2, "appInfoId");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(Long value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(Long value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(Long value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(Long value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(Long value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(Long value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<Long> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<Long> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(Long value1, Long value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(Long value1, Long value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andLoginIdIsNull() {
            addCriterion("login_id is null");
            return (Criteria) this;
        }

        public Criteria andLoginIdIsNotNull() {
            addCriterion("login_id is not null");
            return (Criteria) this;
        }

        public Criteria andLoginIdEqualTo(Long value) {
            addCriterion("login_id =", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotEqualTo(Long value) {
            addCriterion("login_id <>", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThan(Long value) {
            addCriterion("login_id >", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThanOrEqualTo(Long value) {
            addCriterion("login_id >=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThan(Long value) {
            addCriterion("login_id <", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThanOrEqualTo(Long value) {
            addCriterion("login_id <=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdIn(List<Long> values) {
            addCriterion("login_id in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotIn(List<Long> values) {
            addCriterion("login_id not in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdBetween(Long value1, Long value2) {
            addCriterion("login_id between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotBetween(Long value1, Long value2) {
            addCriterion("login_id not between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andAppComNameIsNull() {
            addCriterion("app_com_name is null");
            return (Criteria) this;
        }

        public Criteria andAppComNameIsNotNull() {
            addCriterion("app_com_name is not null");
            return (Criteria) this;
        }

        public Criteria andAppComNameEqualTo(String value) {
            addCriterion("app_com_name =", value, "appComName");
            return (Criteria) this;
        }

        public Criteria andAppComNameNotEqualTo(String value) {
            addCriterion("app_com_name <>", value, "appComName");
            return (Criteria) this;
        }

        public Criteria andAppComNameGreaterThan(String value) {
            addCriterion("app_com_name >", value, "appComName");
            return (Criteria) this;
        }

        public Criteria andAppComNameGreaterThanOrEqualTo(String value) {
            addCriterion("app_com_name >=", value, "appComName");
            return (Criteria) this;
        }

        public Criteria andAppComNameLessThan(String value) {
            addCriterion("app_com_name <", value, "appComName");
            return (Criteria) this;
        }

        public Criteria andAppComNameLessThanOrEqualTo(String value) {
            addCriterion("app_com_name <=", value, "appComName");
            return (Criteria) this;
        }

        public Criteria andAppComNameLike(String value) {
            addCriterion("app_com_name like", value, "appComName");
            return (Criteria) this;
        }

        public Criteria andAppComNameNotLike(String value) {
            addCriterion("app_com_name not like", value, "appComName");
            return (Criteria) this;
        }

        public Criteria andAppComNameIn(List<String> values) {
            addCriterion("app_com_name in", values, "appComName");
            return (Criteria) this;
        }

        public Criteria andAppComNameNotIn(List<String> values) {
            addCriterion("app_com_name not in", values, "appComName");
            return (Criteria) this;
        }

        public Criteria andAppComNameBetween(String value1, String value2) {
            addCriterion("app_com_name between", value1, value2, "appComName");
            return (Criteria) this;
        }

        public Criteria andAppComNameNotBetween(String value1, String value2) {
            addCriterion("app_com_name not between", value1, value2, "appComName");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoIsNull() {
            addCriterion("app_com_org_no is null");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoIsNotNull() {
            addCriterion("app_com_org_no is not null");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoEqualTo(String value) {
            addCriterion("app_com_org_no =", value, "appComOrgNo");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoNotEqualTo(String value) {
            addCriterion("app_com_org_no <>", value, "appComOrgNo");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoGreaterThan(String value) {
            addCriterion("app_com_org_no >", value, "appComOrgNo");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoGreaterThanOrEqualTo(String value) {
            addCriterion("app_com_org_no >=", value, "appComOrgNo");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoLessThan(String value) {
            addCriterion("app_com_org_no <", value, "appComOrgNo");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoLessThanOrEqualTo(String value) {
            addCriterion("app_com_org_no <=", value, "appComOrgNo");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoLike(String value) {
            addCriterion("app_com_org_no like", value, "appComOrgNo");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoNotLike(String value) {
            addCriterion("app_com_org_no not like", value, "appComOrgNo");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoIn(List<String> values) {
            addCriterion("app_com_org_no in", values, "appComOrgNo");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoNotIn(List<String> values) {
            addCriterion("app_com_org_no not in", values, "appComOrgNo");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoBetween(String value1, String value2) {
            addCriterion("app_com_org_no between", value1, value2, "appComOrgNo");
            return (Criteria) this;
        }

        public Criteria andAppComOrgNoNotBetween(String value1, String value2) {
            addCriterion("app_com_org_no not between", value1, value2, "appComOrgNo");
            return (Criteria) this;
        }

        public Criteria andAppComOrgTypeIsNull() {
            addCriterion("app_com_org_type is null");
            return (Criteria) this;
        }

        public Criteria andAppComOrgTypeIsNotNull() {
            addCriterion("app_com_org_type is not null");
            return (Criteria) this;
        }

        public Criteria andAppComOrgTypeEqualTo(Integer value) {
            addCriterion("app_com_org_type =", value, "appComOrgType");
            return (Criteria) this;
        }

        public Criteria andAppComOrgTypeNotEqualTo(Integer value) {
            addCriterion("app_com_org_type <>", value, "appComOrgType");
            return (Criteria) this;
        }

        public Criteria andAppComOrgTypeGreaterThan(Integer value) {
            addCriterion("app_com_org_type >", value, "appComOrgType");
            return (Criteria) this;
        }

        public Criteria andAppComOrgTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("app_com_org_type >=", value, "appComOrgType");
            return (Criteria) this;
        }

        public Criteria andAppComOrgTypeLessThan(Integer value) {
            addCriterion("app_com_org_type <", value, "appComOrgType");
            return (Criteria) this;
        }

        public Criteria andAppComOrgTypeLessThanOrEqualTo(Integer value) {
            addCriterion("app_com_org_type <=", value, "appComOrgType");
            return (Criteria) this;
        }

        public Criteria andAppComOrgTypeIn(List<Integer> values) {
            addCriterion("app_com_org_type in", values, "appComOrgType");
            return (Criteria) this;
        }

        public Criteria andAppComOrgTypeNotIn(List<Integer> values) {
            addCriterion("app_com_org_type not in", values, "appComOrgType");
            return (Criteria) this;
        }

        public Criteria andAppComOrgTypeBetween(Integer value1, Integer value2) {
            addCriterion("app_com_org_type between", value1, value2, "appComOrgType");
            return (Criteria) this;
        }

        public Criteria andAppComOrgTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("app_com_org_type not between", value1, value2, "appComOrgType");
            return (Criteria) this;
        }

        public Criteria andPartnerNumIsNull() {
            addCriterion("partner_num is null");
            return (Criteria) this;
        }

        public Criteria andPartnerNumIsNotNull() {
            addCriterion("partner_num is not null");
            return (Criteria) this;
        }

        public Criteria andPartnerNumEqualTo(Long value) {
            addCriterion("partner_num =", value, "partnerNum");
            return (Criteria) this;
        }

        public Criteria andPartnerNumNotEqualTo(Long value) {
            addCriterion("partner_num <>", value, "partnerNum");
            return (Criteria) this;
        }

        public Criteria andPartnerNumGreaterThan(Long value) {
            addCriterion("partner_num >", value, "partnerNum");
            return (Criteria) this;
        }

        public Criteria andPartnerNumGreaterThanOrEqualTo(Long value) {
            addCriterion("partner_num >=", value, "partnerNum");
            return (Criteria) this;
        }

        public Criteria andPartnerNumLessThan(Long value) {
            addCriterion("partner_num <", value, "partnerNum");
            return (Criteria) this;
        }

        public Criteria andPartnerNumLessThanOrEqualTo(Long value) {
            addCriterion("partner_num <=", value, "partnerNum");
            return (Criteria) this;
        }

        public Criteria andPartnerNumIn(List<Long> values) {
            addCriterion("partner_num in", values, "partnerNum");
            return (Criteria) this;
        }

        public Criteria andPartnerNumNotIn(List<Long> values) {
            addCriterion("partner_num not in", values, "partnerNum");
            return (Criteria) this;
        }

        public Criteria andPartnerNumBetween(Long value1, Long value2) {
            addCriterion("partner_num between", value1, value2, "partnerNum");
            return (Criteria) this;
        }

        public Criteria andPartnerNumNotBetween(Long value1, Long value2) {
            addCriterion("partner_num not between", value1, value2, "partnerNum");
            return (Criteria) this;
        }

        public Criteria andAppComFoundingTimeIsNull() {
            addCriterion("app_com_founding_time is null");
            return (Criteria) this;
        }

        public Criteria andAppComFoundingTimeIsNotNull() {
            addCriterion("app_com_founding_time is not null");
            return (Criteria) this;
        }

        public Criteria andAppComFoundingTimeEqualTo(Date value) {
            addCriterion("app_com_founding_time =", value, "appComFoundingTime");
            return (Criteria) this;
        }

        public Criteria andAppComFoundingTimeNotEqualTo(Date value) {
            addCriterion("app_com_founding_time <>", value, "appComFoundingTime");
            return (Criteria) this;
        }

        public Criteria andAppComFoundingTimeGreaterThan(Date value) {
            addCriterion("app_com_founding_time >", value, "appComFoundingTime");
            return (Criteria) this;
        }

        public Criteria andAppComFoundingTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("app_com_founding_time >=", value, "appComFoundingTime");
            return (Criteria) this;
        }

        public Criteria andAppComFoundingTimeLessThan(Date value) {
            addCriterion("app_com_founding_time <", value, "appComFoundingTime");
            return (Criteria) this;
        }

        public Criteria andAppComFoundingTimeLessThanOrEqualTo(Date value) {
            addCriterion("app_com_founding_time <=", value, "appComFoundingTime");
            return (Criteria) this;
        }

        public Criteria andAppComFoundingTimeIn(List<Date> values) {
            addCriterion("app_com_founding_time in", values, "appComFoundingTime");
            return (Criteria) this;
        }

        public Criteria andAppComFoundingTimeNotIn(List<Date> values) {
            addCriterion("app_com_founding_time not in", values, "appComFoundingTime");
            return (Criteria) this;
        }

        public Criteria andAppComFoundingTimeBetween(Date value1, Date value2) {
            addCriterion("app_com_founding_time between", value1, value2, "appComFoundingTime");
            return (Criteria) this;
        }

        public Criteria andAppComFoundingTimeNotBetween(Date value1, Date value2) {
            addCriterion("app_com_founding_time not between", value1, value2, "appComFoundingTime");
            return (Criteria) this;
        }

        public Criteria andAppComEmployeNumIsNull() {
            addCriterion("app_com_employe_num is null");
            return (Criteria) this;
        }

        public Criteria andAppComEmployeNumIsNotNull() {
            addCriterion("app_com_employe_num is not null");
            return (Criteria) this;
        }

        public Criteria andAppComEmployeNumEqualTo(Long value) {
            addCriterion("app_com_employe_num =", value, "appComEmployeNum");
            return (Criteria) this;
        }

        public Criteria andAppComEmployeNumNotEqualTo(Long value) {
            addCriterion("app_com_employe_num <>", value, "appComEmployeNum");
            return (Criteria) this;
        }

        public Criteria andAppComEmployeNumGreaterThan(Long value) {
            addCriterion("app_com_employe_num >", value, "appComEmployeNum");
            return (Criteria) this;
        }

        public Criteria andAppComEmployeNumGreaterThanOrEqualTo(Long value) {
            addCriterion("app_com_employe_num >=", value, "appComEmployeNum");
            return (Criteria) this;
        }

        public Criteria andAppComEmployeNumLessThan(Long value) {
            addCriterion("app_com_employe_num <", value, "appComEmployeNum");
            return (Criteria) this;
        }

        public Criteria andAppComEmployeNumLessThanOrEqualTo(Long value) {
            addCriterion("app_com_employe_num <=", value, "appComEmployeNum");
            return (Criteria) this;
        }

        public Criteria andAppComEmployeNumIn(List<Long> values) {
            addCriterion("app_com_employe_num in", values, "appComEmployeNum");
            return (Criteria) this;
        }

        public Criteria andAppComEmployeNumNotIn(List<Long> values) {
            addCriterion("app_com_employe_num not in", values, "appComEmployeNum");
            return (Criteria) this;
        }

        public Criteria andAppComEmployeNumBetween(Long value1, Long value2) {
            addCriterion("app_com_employe_num between", value1, value2, "appComEmployeNum");
            return (Criteria) this;
        }

        public Criteria andAppComEmployeNumNotBetween(Long value1, Long value2) {
            addCriterion("app_com_employe_num not between", value1, value2, "appComEmployeNum");
            return (Criteria) this;
        }

        public Criteria andAppComAddressIsNull() {
            addCriterion("app_com_address is null");
            return (Criteria) this;
        }

        public Criteria andAppComAddressIsNotNull() {
            addCriterion("app_com_address is not null");
            return (Criteria) this;
        }

        public Criteria andAppComAddressEqualTo(String value) {
            addCriterion("app_com_address =", value, "appComAddress");
            return (Criteria) this;
        }

        public Criteria andAppComAddressNotEqualTo(String value) {
            addCriterion("app_com_address <>", value, "appComAddress");
            return (Criteria) this;
        }

        public Criteria andAppComAddressGreaterThan(String value) {
            addCriterion("app_com_address >", value, "appComAddress");
            return (Criteria) this;
        }

        public Criteria andAppComAddressGreaterThanOrEqualTo(String value) {
            addCriterion("app_com_address >=", value, "appComAddress");
            return (Criteria) this;
        }

        public Criteria andAppComAddressLessThan(String value) {
            addCriterion("app_com_address <", value, "appComAddress");
            return (Criteria) this;
        }

        public Criteria andAppComAddressLessThanOrEqualTo(String value) {
            addCriterion("app_com_address <=", value, "appComAddress");
            return (Criteria) this;
        }

        public Criteria andAppComAddressLike(String value) {
            addCriterion("app_com_address like", value, "appComAddress");
            return (Criteria) this;
        }

        public Criteria andAppComAddressNotLike(String value) {
            addCriterion("app_com_address not like", value, "appComAddress");
            return (Criteria) this;
        }

        public Criteria andAppComAddressIn(List<String> values) {
            addCriterion("app_com_address in", values, "appComAddress");
            return (Criteria) this;
        }

        public Criteria andAppComAddressNotIn(List<String> values) {
            addCriterion("app_com_address not in", values, "appComAddress");
            return (Criteria) this;
        }

        public Criteria andAppComAddressBetween(String value1, String value2) {
            addCriterion("app_com_address between", value1, value2, "appComAddress");
            return (Criteria) this;
        }

        public Criteria andAppComAddressNotBetween(String value1, String value2) {
            addCriterion("app_com_address not between", value1, value2, "appComAddress");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeIsNull() {
            addCriterion("app_com_zip_code is null");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeIsNotNull() {
            addCriterion("app_com_zip_code is not null");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeEqualTo(String value) {
            addCriterion("app_com_zip_code =", value, "appComZipCode");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeNotEqualTo(String value) {
            addCriterion("app_com_zip_code <>", value, "appComZipCode");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeGreaterThan(String value) {
            addCriterion("app_com_zip_code >", value, "appComZipCode");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeGreaterThanOrEqualTo(String value) {
            addCriterion("app_com_zip_code >=", value, "appComZipCode");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeLessThan(String value) {
            addCriterion("app_com_zip_code <", value, "appComZipCode");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeLessThanOrEqualTo(String value) {
            addCriterion("app_com_zip_code <=", value, "appComZipCode");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeLike(String value) {
            addCriterion("app_com_zip_code like", value, "appComZipCode");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeNotLike(String value) {
            addCriterion("app_com_zip_code not like", value, "appComZipCode");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeIn(List<String> values) {
            addCriterion("app_com_zip_code in", values, "appComZipCode");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeNotIn(List<String> values) {
            addCriterion("app_com_zip_code not in", values, "appComZipCode");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeBetween(String value1, String value2) {
            addCriterion("app_com_zip_code between", value1, value2, "appComZipCode");
            return (Criteria) this;
        }

        public Criteria andAppComZipCodeNotBetween(String value1, String value2) {
            addCriterion("app_com_zip_code not between", value1, value2, "appComZipCode");
            return (Criteria) this;
        }

        public Criteria andContactNameIsNull() {
            addCriterion("contact_name is null");
            return (Criteria) this;
        }

        public Criteria andContactNameIsNotNull() {
            addCriterion("contact_name is not null");
            return (Criteria) this;
        }

        public Criteria andContactNameEqualTo(String value) {
            addCriterion("contact_name =", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotEqualTo(String value) {
            addCriterion("contact_name <>", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameGreaterThan(String value) {
            addCriterion("contact_name >", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameGreaterThanOrEqualTo(String value) {
            addCriterion("contact_name >=", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameLessThan(String value) {
            addCriterion("contact_name <", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameLessThanOrEqualTo(String value) {
            addCriterion("contact_name <=", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameLike(String value) {
            addCriterion("contact_name like", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotLike(String value) {
            addCriterion("contact_name not like", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameIn(List<String> values) {
            addCriterion("contact_name in", values, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotIn(List<String> values) {
            addCriterion("contact_name not in", values, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameBetween(String value1, String value2) {
            addCriterion("contact_name between", value1, value2, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotBetween(String value1, String value2) {
            addCriterion("contact_name not between", value1, value2, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactTelIsNull() {
            addCriterion("contact_tel is null");
            return (Criteria) this;
        }

        public Criteria andContactTelIsNotNull() {
            addCriterion("contact_tel is not null");
            return (Criteria) this;
        }

        public Criteria andContactTelEqualTo(String value) {
            addCriterion("contact_tel =", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelNotEqualTo(String value) {
            addCriterion("contact_tel <>", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelGreaterThan(String value) {
            addCriterion("contact_tel >", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelGreaterThanOrEqualTo(String value) {
            addCriterion("contact_tel >=", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelLessThan(String value) {
            addCriterion("contact_tel <", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelLessThanOrEqualTo(String value) {
            addCriterion("contact_tel <=", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelLike(String value) {
            addCriterion("contact_tel like", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelNotLike(String value) {
            addCriterion("contact_tel not like", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelIn(List<String> values) {
            addCriterion("contact_tel in", values, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelNotIn(List<String> values) {
            addCriterion("contact_tel not in", values, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelBetween(String value1, String value2) {
            addCriterion("contact_tel between", value1, value2, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelNotBetween(String value1, String value2) {
            addCriterion("contact_tel not between", value1, value2, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactEmailIsNull() {
            addCriterion("contact_email is null");
            return (Criteria) this;
        }

        public Criteria andContactEmailIsNotNull() {
            addCriterion("contact_email is not null");
            return (Criteria) this;
        }

        public Criteria andContactEmailEqualTo(String value) {
            addCriterion("contact_email =", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailNotEqualTo(String value) {
            addCriterion("contact_email <>", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailGreaterThan(String value) {
            addCriterion("contact_email >", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailGreaterThanOrEqualTo(String value) {
            addCriterion("contact_email >=", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailLessThan(String value) {
            addCriterion("contact_email <", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailLessThanOrEqualTo(String value) {
            addCriterion("contact_email <=", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailLike(String value) {
            addCriterion("contact_email like", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailNotLike(String value) {
            addCriterion("contact_email not like", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailIn(List<String> values) {
            addCriterion("contact_email in", values, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailNotIn(List<String> values) {
            addCriterion("contact_email not in", values, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailBetween(String value1, String value2) {
            addCriterion("contact_email between", value1, value2, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailNotBetween(String value1, String value2) {
            addCriterion("contact_email not between", value1, value2, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNull() {
            addCriterion("create_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNotNull() {
            addCriterion("create_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIdEqualTo(Long value) {
            addCriterion("create_id =", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotEqualTo(Long value) {
            addCriterion("create_id <>", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThan(Long value) {
            addCriterion("create_id >", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("create_id >=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThan(Long value) {
            addCriterion("create_id <", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThanOrEqualTo(Long value) {
            addCriterion("create_id <=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdIn(List<Long> values) {
            addCriterion("create_id in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotIn(List<Long> values) {
            addCriterion("create_id not in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdBetween(Long value1, Long value2) {
            addCriterion("create_id between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotBetween(Long value1, Long value2) {
            addCriterion("create_id not between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNull() {
            addCriterion("modify_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNotNull() {
            addCriterion("modify_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyIdEqualTo(Long value) {
            addCriterion("modify_id =", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotEqualTo(Long value) {
            addCriterion("modify_id <>", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThan(Long value) {
            addCriterion("modify_id >", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modify_id >=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThan(Long value) {
            addCriterion("modify_id <", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThanOrEqualTo(Long value) {
            addCriterion("modify_id <=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdIn(List<Long> values) {
            addCriterion("modify_id in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotIn(List<Long> values) {
            addCriterion("modify_id not in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdBetween(Long value1, Long value2) {
            addCriterion("modify_id between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotBetween(Long value1, Long value2) {
            addCriterion("modify_id not between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andCreatorNameIsNull() {
            addCriterion("creator_name is null");
            return (Criteria) this;
        }

        public Criteria andCreatorNameIsNotNull() {
            addCriterion("creator_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorNameEqualTo(String value) {
            addCriterion("creator_name =", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotEqualTo(String value) {
            addCriterion("creator_name <>", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameGreaterThan(String value) {
            addCriterion("creator_name >", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameGreaterThanOrEqualTo(String value) {
            addCriterion("creator_name >=", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameLessThan(String value) {
            addCriterion("creator_name <", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameLessThanOrEqualTo(String value) {
            addCriterion("creator_name <=", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameLike(String value) {
            addCriterion("creator_name like", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotLike(String value) {
            addCriterion("creator_name not like", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameIn(List<String> values) {
            addCriterion("creator_name in", values, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotIn(List<String> values) {
            addCriterion("creator_name not in", values, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameBetween(String value1, String value2) {
            addCriterion("creator_name between", value1, value2, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotBetween(String value1, String value2) {
            addCriterion("creator_name not between", value1, value2, "creatorName");
            return (Criteria) this;
        }

        public Criteria andModifierNameIsNull() {
            addCriterion("modifier_name is null");
            return (Criteria) this;
        }

        public Criteria andModifierNameIsNotNull() {
            addCriterion("modifier_name is not null");
            return (Criteria) this;
        }

        public Criteria andModifierNameEqualTo(String value) {
            addCriterion("modifier_name =", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameNotEqualTo(String value) {
            addCriterion("modifier_name <>", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameGreaterThan(String value) {
            addCriterion("modifier_name >", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameGreaterThanOrEqualTo(String value) {
            addCriterion("modifier_name >=", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameLessThan(String value) {
            addCriterion("modifier_name <", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameLessThanOrEqualTo(String value) {
            addCriterion("modifier_name <=", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameLike(String value) {
            addCriterion("modifier_name like", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameNotLike(String value) {
            addCriterion("modifier_name not like", value, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameIn(List<String> values) {
            addCriterion("modifier_name in", values, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameNotIn(List<String> values) {
            addCriterion("modifier_name not in", values, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameBetween(String value1, String value2) {
            addCriterion("modifier_name between", value1, value2, "modifierName");
            return (Criteria) this;
        }

        public Criteria andModifierNameNotBetween(String value1, String value2) {
            addCriterion("modifier_name not between", value1, value2, "modifierName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table insure_applicant_info
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 30 11:21:21 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}