package com.muses.entity;

import java.util.Date;

public class UserLoginInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.login_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Long loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.user_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.login_passwd
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String loginPasswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.organization_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Long organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.credit_no
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String creditNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.organization_type
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Integer organizationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.partner_num
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Integer partnerNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.staff_num
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Integer staffNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.register_date
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Date registerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.short_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.business_region
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String businessRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.tel
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.fax
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.zip
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.email
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.business_license_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Long businessLicenseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.practicing_certificatep_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Long practicingCertificatepId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.loss_flag
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Integer lossFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.overseas
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Integer overseas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.protocol_no
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String protocolNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.protocol_expiry_date
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Date protocolExpiryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.protocol_end_date
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Date protocolEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.taxpayer_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String taxpayerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.contacts_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String contactsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.contacts_email
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String contactsEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.contacts_mobile
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String contactsMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.bank_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.bank_account
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.invoice_mobile
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String invoiceMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.invoice_address
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String invoiceAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.receive_person
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String receivePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.receive_tel
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String receiveTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.freeze_flag
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Integer freezeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.last_login_date
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Date lastLoginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.adder_no
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Long adderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.updater_no
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Long updaterNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.adder_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String adderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.updater_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private String updaterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.add_time
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_info.update_time
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.login_id
     *
     * @return the value of user_login_info.login_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Long getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.login_id
     *
     * @param loginId the value for user_login_info.login_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setLoginId(Long loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.user_name
     *
     * @return the value of user_login_info.user_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.user_name
     *
     * @param userName the value for user_login_info.user_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.name
     *
     * @return the value of user_login_info.name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.name
     *
     * @param name the value for user_login_info.name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.login_passwd
     *
     * @return the value of user_login_info.login_passwd
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getLoginPasswd() {
        return loginPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.login_passwd
     *
     * @param loginPasswd the value for user_login_info.login_passwd
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setLoginPasswd(String loginPasswd) {
        this.loginPasswd = loginPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.organization_id
     *
     * @return the value of user_login_info.organization_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.organization_id
     *
     * @param organizationId the value for user_login_info.organization_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.credit_no
     *
     * @return the value of user_login_info.credit_no
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getCreditNo() {
        return creditNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.credit_no
     *
     * @param creditNo the value for user_login_info.credit_no
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setCreditNo(String creditNo) {
        this.creditNo = creditNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.organization_type
     *
     * @return the value of user_login_info.organization_type
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Integer getOrganizationType() {
        return organizationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.organization_type
     *
     * @param organizationType the value for user_login_info.organization_type
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setOrganizationType(Integer organizationType) {
        this.organizationType = organizationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.partner_num
     *
     * @return the value of user_login_info.partner_num
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Integer getPartnerNum() {
        return partnerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.partner_num
     *
     * @param partnerNum the value for user_login_info.partner_num
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setPartnerNum(Integer partnerNum) {
        this.partnerNum = partnerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.staff_num
     *
     * @return the value of user_login_info.staff_num
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Integer getStaffNum() {
        return staffNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.staff_num
     *
     * @param staffNum the value for user_login_info.staff_num
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setStaffNum(Integer staffNum) {
        this.staffNum = staffNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.register_date
     *
     * @return the value of user_login_info.register_date
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.register_date
     *
     * @param registerDate the value for user_login_info.register_date
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.short_name
     *
     * @return the value of user_login_info.short_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.short_name
     *
     * @param shortName the value for user_login_info.short_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.business_region
     *
     * @return the value of user_login_info.business_region
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getBusinessRegion() {
        return businessRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.business_region
     *
     * @param businessRegion the value for user_login_info.business_region
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setBusinessRegion(String businessRegion) {
        this.businessRegion = businessRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.tel
     *
     * @return the value of user_login_info.tel
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.tel
     *
     * @param tel the value for user_login_info.tel
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.fax
     *
     * @return the value of user_login_info.fax
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.fax
     *
     * @param fax the value for user_login_info.fax
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.zip
     *
     * @return the value of user_login_info.zip
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.zip
     *
     * @param zip the value for user_login_info.zip
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.email
     *
     * @return the value of user_login_info.email
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.email
     *
     * @param email the value for user_login_info.email
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.business_license_id
     *
     * @return the value of user_login_info.business_license_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Long getBusinessLicenseId() {
        return businessLicenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.business_license_id
     *
     * @param businessLicenseId the value for user_login_info.business_license_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setBusinessLicenseId(Long businessLicenseId) {
        this.businessLicenseId = businessLicenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.practicing_certificatep_id
     *
     * @return the value of user_login_info.practicing_certificatep_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Long getPracticingCertificatepId() {
        return practicingCertificatepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.practicing_certificatep_id
     *
     * @param practicingCertificatepId the value for user_login_info.practicing_certificatep_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setPracticingCertificatepId(Long practicingCertificatepId) {
        this.practicingCertificatepId = practicingCertificatepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.loss_flag
     *
     * @return the value of user_login_info.loss_flag
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Integer getLossFlag() {
        return lossFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.loss_flag
     *
     * @param lossFlag the value for user_login_info.loss_flag
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setLossFlag(Integer lossFlag) {
        this.lossFlag = lossFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.overseas
     *
     * @return the value of user_login_info.overseas
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Integer getOverseas() {
        return overseas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.overseas
     *
     * @param overseas the value for user_login_info.overseas
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setOverseas(Integer overseas) {
        this.overseas = overseas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.protocol_no
     *
     * @return the value of user_login_info.protocol_no
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getProtocolNo() {
        return protocolNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.protocol_no
     *
     * @param protocolNo the value for user_login_info.protocol_no
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setProtocolNo(String protocolNo) {
        this.protocolNo = protocolNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.protocol_expiry_date
     *
     * @return the value of user_login_info.protocol_expiry_date
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Date getProtocolExpiryDate() {
        return protocolExpiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.protocol_expiry_date
     *
     * @param protocolExpiryDate the value for user_login_info.protocol_expiry_date
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setProtocolExpiryDate(Date protocolExpiryDate) {
        this.protocolExpiryDate = protocolExpiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.protocol_end_date
     *
     * @return the value of user_login_info.protocol_end_date
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Date getProtocolEndDate() {
        return protocolEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.protocol_end_date
     *
     * @param protocolEndDate the value for user_login_info.protocol_end_date
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setProtocolEndDate(Date protocolEndDate) {
        this.protocolEndDate = protocolEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.taxpayer_id
     *
     * @return the value of user_login_info.taxpayer_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getTaxpayerId() {
        return taxpayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.taxpayer_id
     *
     * @param taxpayerId the value for user_login_info.taxpayer_id
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setTaxpayerId(String taxpayerId) {
        this.taxpayerId = taxpayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.contacts_name
     *
     * @return the value of user_login_info.contacts_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getContactsName() {
        return contactsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.contacts_name
     *
     * @param contactsName the value for user_login_info.contacts_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setContactsName(String contactsName) {
        this.contactsName = contactsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.contacts_email
     *
     * @return the value of user_login_info.contacts_email
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getContactsEmail() {
        return contactsEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.contacts_email
     *
     * @param contactsEmail the value for user_login_info.contacts_email
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setContactsEmail(String contactsEmail) {
        this.contactsEmail = contactsEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.contacts_mobile
     *
     * @return the value of user_login_info.contacts_mobile
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getContactsMobile() {
        return contactsMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.contacts_mobile
     *
     * @param contactsMobile the value for user_login_info.contacts_mobile
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setContactsMobile(String contactsMobile) {
        this.contactsMobile = contactsMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.bank_name
     *
     * @return the value of user_login_info.bank_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.bank_name
     *
     * @param bankName the value for user_login_info.bank_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.bank_account
     *
     * @return the value of user_login_info.bank_account
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.bank_account
     *
     * @param bankAccount the value for user_login_info.bank_account
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.invoice_mobile
     *
     * @return the value of user_login_info.invoice_mobile
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getInvoiceMobile() {
        return invoiceMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.invoice_mobile
     *
     * @param invoiceMobile the value for user_login_info.invoice_mobile
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setInvoiceMobile(String invoiceMobile) {
        this.invoiceMobile = invoiceMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.invoice_address
     *
     * @return the value of user_login_info.invoice_address
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getInvoiceAddress() {
        return invoiceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.invoice_address
     *
     * @param invoiceAddress the value for user_login_info.invoice_address
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setInvoiceAddress(String invoiceAddress) {
        this.invoiceAddress = invoiceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.receive_person
     *
     * @return the value of user_login_info.receive_person
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getReceivePerson() {
        return receivePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.receive_person
     *
     * @param receivePerson the value for user_login_info.receive_person
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setReceivePerson(String receivePerson) {
        this.receivePerson = receivePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.receive_tel
     *
     * @return the value of user_login_info.receive_tel
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getReceiveTel() {
        return receiveTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.receive_tel
     *
     * @param receiveTel the value for user_login_info.receive_tel
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setReceiveTel(String receiveTel) {
        this.receiveTel = receiveTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.freeze_flag
     *
     * @return the value of user_login_info.freeze_flag
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Integer getFreezeFlag() {
        return freezeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.freeze_flag
     *
     * @param freezeFlag the value for user_login_info.freeze_flag
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setFreezeFlag(Integer freezeFlag) {
        this.freezeFlag = freezeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.last_login_date
     *
     * @return the value of user_login_info.last_login_date
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.last_login_date
     *
     * @param lastLoginDate the value for user_login_info.last_login_date
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.adder_no
     *
     * @return the value of user_login_info.adder_no
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Long getAdderNo() {
        return adderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.adder_no
     *
     * @param adderNo the value for user_login_info.adder_no
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setAdderNo(Long adderNo) {
        this.adderNo = adderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.updater_no
     *
     * @return the value of user_login_info.updater_no
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Long getUpdaterNo() {
        return updaterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.updater_no
     *
     * @param updaterNo the value for user_login_info.updater_no
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setUpdaterNo(Long updaterNo) {
        this.updaterNo = updaterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.adder_name
     *
     * @return the value of user_login_info.adder_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.adder_name
     *
     * @param adderName the value for user_login_info.adder_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.updater_name
     *
     * @return the value of user_login_info.updater_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.updater_name
     *
     * @param updaterName the value for user_login_info.updater_name
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.add_time
     *
     * @return the value of user_login_info.add_time
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.add_time
     *
     * @param addTime the value for user_login_info.add_time
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_info.update_time
     *
     * @return the value of user_login_info.update_time
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_info.update_time
     *
     * @param updateTime the value for user_login_info.update_time
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}