package cn.muses.entity;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS.STUDENT.STUDENT_ID
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    private Long studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS.STUDENT.NAME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS.STUDENT.MOBILE
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS.STUDENT.CREATE_TIME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS.STUDENT.MODIFY_TIME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS.STUDENT.CREATE_ID
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    private Long createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS.STUDENT.MODIFY_ID
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    private Long modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS.STUDENT.CREATOR_NAME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS.STUDENT.MODIFIER_NAME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    private String modifierName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS.STUDENT.STUDENT_ID
     *
     * @return the value of INS.STUDENT.STUDENT_ID
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS.STUDENT.STUDENT_ID
     *
     * @param studentId the value for INS.STUDENT.STUDENT_ID
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS.STUDENT.NAME
     *
     * @return the value of INS.STUDENT.NAME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS.STUDENT.NAME
     *
     * @param name the value for INS.STUDENT.NAME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS.STUDENT.MOBILE
     *
     * @return the value of INS.STUDENT.MOBILE
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS.STUDENT.MOBILE
     *
     * @param mobile the value for INS.STUDENT.MOBILE
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS.STUDENT.CREATE_TIME
     *
     * @return the value of INS.STUDENT.CREATE_TIME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS.STUDENT.CREATE_TIME
     *
     * @param createTime the value for INS.STUDENT.CREATE_TIME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS.STUDENT.MODIFY_TIME
     *
     * @return the value of INS.STUDENT.MODIFY_TIME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS.STUDENT.MODIFY_TIME
     *
     * @param modifyTime the value for INS.STUDENT.MODIFY_TIME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS.STUDENT.CREATE_ID
     *
     * @return the value of INS.STUDENT.CREATE_ID
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS.STUDENT.CREATE_ID
     *
     * @param createId the value for INS.STUDENT.CREATE_ID
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS.STUDENT.MODIFY_ID
     *
     * @return the value of INS.STUDENT.MODIFY_ID
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public Long getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS.STUDENT.MODIFY_ID
     *
     * @param modifyId the value for INS.STUDENT.MODIFY_ID
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public void setModifyId(Long modifyId) {
        this.modifyId = modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS.STUDENT.CREATOR_NAME
     *
     * @return the value of INS.STUDENT.CREATOR_NAME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS.STUDENT.CREATOR_NAME
     *
     * @param creatorName the value for INS.STUDENT.CREATOR_NAME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS.STUDENT.MODIFIER_NAME
     *
     * @return the value of INS.STUDENT.MODIFIER_NAME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS.STUDENT.MODIFIER_NAME
     *
     * @param modifierName the value for INS.STUDENT.MODIFIER_NAME
     *
     * @mbggenerated Wed Nov 21 13:46:42 CST 2018
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName;
    }
}