package com.muses.mapper;

import com.muses.common.orm.mybatis.MyBatisRepository;
import com.muses.entity.InsureApplicantInfo;
import com.muses.entity.InsureApplicantInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@MyBatisRepository
public interface InsureApplicantInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    long countByCriteria(InsureApplicantInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    int deleteByCriteria(InsureApplicantInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    int deleteByPrimaryKey(Long appInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    int insert(InsureApplicantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    int insertSelective(InsureApplicantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    List<InsureApplicantInfo> selectByCriteriaWithRowbounds(InsureApplicantInfoCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    List<InsureApplicantInfo> selectByCriteria(InsureApplicantInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    InsureApplicantInfo selectByPrimaryKey(Long appInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    int updateByCriteriaSelective(@Param("record") InsureApplicantInfo record, @Param("example") InsureApplicantInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    int updateByCriteria(@Param("record") InsureApplicantInfo record, @Param("example") InsureApplicantInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    int updateByPrimaryKeySelective(InsureApplicantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_applicant_info
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    int updateByPrimaryKey(InsureApplicantInfo record);
}