package com.muses.mapper;

import com.muses.common.orm.mybatis.MyBatisRepository;
import com.muses.entity.UserLoginInfo;
import com.muses.entity.UserLoginInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@MyBatisRepository
public interface UserLoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    long countByCriteria(UserLoginInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    int deleteByCriteria(UserLoginInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    int deleteByPrimaryKey(Long loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    int insert(UserLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    int insertSelective(UserLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    List<UserLoginInfo> selectByCriteriaWithRowbounds(UserLoginInfoCriteria criteria, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    List<UserLoginInfo> selectByCriteria(UserLoginInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    UserLoginInfo selectByPrimaryKey(Long loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    int updateByCriteriaSelective(@Param("record") UserLoginInfo record, @Param("example") UserLoginInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    int updateByCriteria(@Param("record") UserLoginInfo record, @Param("example") UserLoginInfoCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    int updateByPrimaryKeySelective(UserLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbg.generated Fri Nov 30 11:45:52 CST 2018
     */
    int updateByPrimaryKey(UserLoginInfo record);
}