package cn.muses.entity;

import java.util.Date;

public class InsureApplicantInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.app_info_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private Long appInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.app_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.login_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private Long loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.app_com_name
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private String appComName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.app_com_org_no
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private String appComOrgNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.app_com_org_type
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private Integer appComOrgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.partner_num
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private Long partnerNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.app_com_founding_time
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private Date appComFoundingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.app_com_employe_num
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private Long appComEmployeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.app_com_address
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private String appComAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.app_com_zip_code
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private String appComZipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.contact_name
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.contact_tel
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private String contactTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.contact_email
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private String contactEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.create_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.modify_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private Long modifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.creator_name
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.modifier_name
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.create_time
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure_applicant_info.modify_time
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.app_info_id
     *
     * @return the value of insure_applicant_info.app_info_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Long getAppInfoId() {
        return appInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.app_info_id
     *
     * @param appInfoId the value for insure_applicant_info.app_info_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setAppInfoId(Long appInfoId) {
        this.appInfoId = appInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.app_id
     *
     * @return the value of insure_applicant_info.app_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.app_id
     *
     * @param appId the value for insure_applicant_info.app_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.login_id
     *
     * @return the value of insure_applicant_info.login_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Long getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.login_id
     *
     * @param loginId the value for insure_applicant_info.login_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setLoginId(Long loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.app_com_name
     *
     * @return the value of insure_applicant_info.app_com_name
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public String getAppComName() {
        return appComName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.app_com_name
     *
     * @param appComName the value for insure_applicant_info.app_com_name
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setAppComName(String appComName) {
        this.appComName = appComName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.app_com_org_no
     *
     * @return the value of insure_applicant_info.app_com_org_no
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public String getAppComOrgNo() {
        return appComOrgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.app_com_org_no
     *
     * @param appComOrgNo the value for insure_applicant_info.app_com_org_no
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setAppComOrgNo(String appComOrgNo) {
        this.appComOrgNo = appComOrgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.app_com_org_type
     *
     * @return the value of insure_applicant_info.app_com_org_type
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Integer getAppComOrgType() {
        return appComOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.app_com_org_type
     *
     * @param appComOrgType the value for insure_applicant_info.app_com_org_type
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setAppComOrgType(Integer appComOrgType) {
        this.appComOrgType = appComOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.partner_num
     *
     * @return the value of insure_applicant_info.partner_num
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Long getPartnerNum() {
        return partnerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.partner_num
     *
     * @param partnerNum the value for insure_applicant_info.partner_num
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setPartnerNum(Long partnerNum) {
        this.partnerNum = partnerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.app_com_founding_time
     *
     * @return the value of insure_applicant_info.app_com_founding_time
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Date getAppComFoundingTime() {
        return appComFoundingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.app_com_founding_time
     *
     * @param appComFoundingTime the value for insure_applicant_info.app_com_founding_time
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setAppComFoundingTime(Date appComFoundingTime) {
        this.appComFoundingTime = appComFoundingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.app_com_employe_num
     *
     * @return the value of insure_applicant_info.app_com_employe_num
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Long getAppComEmployeNum() {
        return appComEmployeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.app_com_employe_num
     *
     * @param appComEmployeNum the value for insure_applicant_info.app_com_employe_num
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setAppComEmployeNum(Long appComEmployeNum) {
        this.appComEmployeNum = appComEmployeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.app_com_address
     *
     * @return the value of insure_applicant_info.app_com_address
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public String getAppComAddress() {
        return appComAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.app_com_address
     *
     * @param appComAddress the value for insure_applicant_info.app_com_address
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setAppComAddress(String appComAddress) {
        this.appComAddress = appComAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.app_com_zip_code
     *
     * @return the value of insure_applicant_info.app_com_zip_code
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public String getAppComZipCode() {
        return appComZipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.app_com_zip_code
     *
     * @param appComZipCode the value for insure_applicant_info.app_com_zip_code
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setAppComZipCode(String appComZipCode) {
        this.appComZipCode = appComZipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.contact_name
     *
     * @return the value of insure_applicant_info.contact_name
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.contact_name
     *
     * @param contactName the value for insure_applicant_info.contact_name
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.contact_tel
     *
     * @return the value of insure_applicant_info.contact_tel
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.contact_tel
     *
     * @param contactTel the value for insure_applicant_info.contact_tel
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.contact_email
     *
     * @return the value of insure_applicant_info.contact_email
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.contact_email
     *
     * @param contactEmail the value for insure_applicant_info.contact_email
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.create_id
     *
     * @return the value of insure_applicant_info.create_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.create_id
     *
     * @param createId the value for insure_applicant_info.create_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.modify_id
     *
     * @return the value of insure_applicant_info.modify_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Long getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.modify_id
     *
     * @param modifyId the value for insure_applicant_info.modify_id
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setModifyId(Long modifyId) {
        this.modifyId = modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.creator_name
     *
     * @return the value of insure_applicant_info.creator_name
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.creator_name
     *
     * @param creatorName the value for insure_applicant_info.creator_name
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.modifier_name
     *
     * @return the value of insure_applicant_info.modifier_name
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.modifier_name
     *
     * @param modifierName the value for insure_applicant_info.modifier_name
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.create_time
     *
     * @return the value of insure_applicant_info.create_time
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.create_time
     *
     * @param createTime the value for insure_applicant_info.create_time
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure_applicant_info.modify_time
     *
     * @return the value of insure_applicant_info.modify_time
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure_applicant_info.modify_time
     *
     * @param modifyTime the value for insure_applicant_info.modify_time
     *
     * @mbg.generated Fri Nov 30 11:21:21 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}
